### ISSUE TITLE
child_frame_id with slashes are shown with underscores

### ISSUE THREAD

**Issue by Ellon** [ros-visualization/rqt_tf_tree#4] opened 2017-06-02 13:41 UTC
When publishing transformations using TF, if the `child_frame_id` name contains `/` it is shown in `rqt_tf_tree` using `_`. For example, I got the following graph:
![tf_slash_underscore_problem](https://cloud.githubusercontent.com/assets/2206351/26727791/4fa8c140-47a8-11e7-92bb-cde2b2178661.png)
while in fact in the `child_frame_id` is named `uav1/cam` as can be seen in `rostopic echo /tf`:
```
$ rostopic echo /tf
(...)
---
transforms:
  -
    header:
      seq: 0
      stamp:
        secs: 1496407680
        nsecs: 788794994
      frame_id: /map
    child_frame_id: /base_link
    transform:
      translation:
        x: 48.4962844849
        y: 79.4509735107
        z: 148.231002808
      rotation:
        x: 0.00100735749584
        y: 0.000460458162706
        z: 0.0110743073747
        w: 0.999938070774
---
transforms:
  -
    header:
      seq: 0
      stamp:
        secs: 1496407680
        nsecs: 805396556
      frame_id: base_link
    child_frame_id: /uav1/cam
    transform:
      translation:
        x: 5.97536563873e-06
        y: 2.32458114624e-06
        z: -4.50760126114e-07
      rotation:
        x: 0.70710682869
        y: -0.70710682869
        z: 4.63135663153e-08
        w: 1.54610066971e-08
(...)
```

This was driving a workmate crazy here in the lab since lookupTransform was not working with the child_frame_id he was seeing in the GUI... :smile:

I think this may be related with [this issue on rqt_graph](https://github.com/ros-visualization/rqt_graph/issues/11).

This problem was found when using ROS Kinetic on Ubuntu 16.04.

**Comment by Ellon** [comment] 2017-06-02 13:55
The pdf generated by `rosrun tf view_frames` has the frame name with `/`as it should be: `/uav1/cam`

**Comment by dirk-thomas** [comment] 2017-07-07 22:17
@ablasdel @130s @Peter9606 FYI. Since you are now the maintainers please Please a look at this when you find some time. Thanks.

**Comment by 130s** [comment] 2017-07-09 07:31
I confirmed that the issue can be resolved with https://github.com/ros-visualization/qt_gui_core/issues/94.

```
term-1$ roslaunch turtle_tf turtle_tf_demo.launch
term-2$ rosrun tf static_transform_publisher 1 1 1 0 0 0 1 /uav1/cam world
```
![screenshot from 2017-07-09 00-28-46](https://user-images.githubusercontent.com/1840401/27991993-a0535f40-643d-11e7-9f1e-e0b3296f46b4.png)

**Comment by gavanderhoorn** [comment] 2017-07-09 11:10
@130s: is the `1` as parent frame of `uav1/cam` correct / expected? Seems strange to me?

**Comment by 130s** [comment] 2017-07-10 06:37
Sorry [that was](https://github.com/ros-visualization/rqt_tf_tree/issues/4#issuecomment-313904308) just wrong arguments passed to `static_transform_publisher`. Retried with better ones:

```
term-1$ roslaunch turtle_tf turtle_tf_demo.launch
term-2$ rosrun tf static_transform_publisher 1 1 1 0 0 0 1 /turtle1 /uav1/cam world
```

![screenshot from 2017-07-09 23-35-11](https://user-images.githubusercontent.com/1840401/28005421-532dd0c0-64ff-11e7-9a21-6866220f27cd.png)

**Comment by dirk-thomas** [comment] 2017-07-10 17:15
Please try the patch proposed in #6 and comment if it fixes the problem for you.

**Comment by Ellon** [comment] 2017-07-10 17:17
I'll try later this week. Thanks!

**Comment by Ellon** [comment] 2017-07-18 13:44
Sorry about the late reply. I confirm #6 fixed the bug.

![rqt_tf_tree_bug_fixed](https://user-images.githubusercontent.com/2206351/28320055-e02c3116-6bcf-11e7-8a4f-c43021713b67.png)


Thanks for proposing the fix!

**Closed** 2017-07-24 18:58 UTC
Labels: bug
